name: Deploy to Google Container Registry

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: prod-examen-24-05-2024
      DOCKER_IMAGE_NAME: prod-examen-24-05-2024/CloudDemo
      TARGET_FRAMEWORK: net6.0
      BUILD_CONFIGURATION: Release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.x"

      - name: Restore dependencies
        run: dotnet restore applications/clouddemo/netcore/CloudDemo.MvcCore.sln

      - name: Build
        run: dotnet build --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore applications/clouddemo/netcore/CloudDemo.MvcCore.sln

      - name: Publish
        run: dotnet publish --configuration ${{ env.BUILD_CONFIGURATION }} --framework ${{ env.TARGET_FRAMEWORK }} --output ./publish applications/clouddemo/netcore/CloudDemo.MvcCore.sln

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Configure Docker for Google Artifact Registry
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.DOCKER_IMAGE_NAME }}:latest -f applications/clouddemo/netcore/Dockerfile .
          docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.DOCKER_IMAGE_NAME }}:latest
